name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    # Current repo
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Run App Production script
      run: |
         chmod +x jenkins/jenkinsfile-microservice-app-production.sh
         jenkins/jenkinsfile-microservice-app-production.sh
      shell: bash
