name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v4

    - name: run bash script
      shell: bash
      run: |
       tree .
       echo "File list complete"
      
    - name: Build docker images
      run: |
        chmod +x jenkins/jenkinsfile-microservice-app-production.sh
        jenkins/jenkinsfile-microservice-app-production.sh
